export type StyleAxis = { label: string; value: number };
export type SourceCharacter = { name: string; role?: string; traits?: string };
export type SourceChapter = { title: string; summary?: string };
export type SourceDigest = {
  version: 1;
  sourceChars: number;
  chunkCount: number;
  chapterCount: number;
  plotSummary: string;
  storyBible: string;
  constraints: string[];
  characters: SourceCharacter[];
  chapterOutline: SourceChapter[];
  format: ProjectFormat;
  episodeCount: number;
  wordsPerEpisode: number;
  scriptLength: ScriptLength;
  narrativePerspective: NarrativePerspective;
  styleEvidence: string;
};
export type WriterStyle = { id: string; name: string; era: string; summary: string; tags: string[]; axes: StyleAxis[]; sample?: string; sourceDigest?: SourceDigest; source?: "curated" | "distilled"; isPublic?: boolean; shareToken?: string };
export type DirectorStyle = { id: string; name: string; summary: string; palette: string[]; descriptor: string; lora?: string; isPublic?: boolean; shareToken?: string };
export type ShotStatus = "draft" | "queued" | "processing" | "complete" | "failed";
export type ScriptLength = "micro" | "short" | "medium" | "long" | "feature" | "series";
export type NarrativePerspective = "third-person" | "first-person" | "observational" | "multi-perspective" | "epistolary" | "unreliable-narrator";
export type ProjectFormat = "single" | "series";
export type ProjectSpec = { format: ProjectFormat; episodeCount: number; wordsPerEpisode: number; totalTargetWords: number };
export type GenerationSpec = ProjectSpec & { storyBible?: string };
export type Character = {
  id: string;
  name: string;
  role: string;
  description: string;
  wardrobe: string;
  accessories?: string;
  goal?: string;
  traits?: string;
  age?: string;
  appearancePrompt?: string;
  imagePrompt?: string;
  negativePrompt?: string;
  referenceAssetId?: string;
  imageProvider?: string;
  imageModel?: string;
  imageStatus?: "draft" | "queued" | "processing" | "complete" | "failed";
};
export type EpisodeContinuity = { summary: string; ending: string; characterState: Character[]; openThreads: string[] };
export type EpisodeSummary = { id: string; number: number; title: string; status: string; outline?: string; logline?: string; script?: string; continuity?: EpisodeContinuity; characterIds?: string[]; sceneCount: number; shotCount: number };
export type EpisodeGenerationContext = {
  episodeNumber: number;
  episodeGoal: string;
  sourceOutline?: string;
  previousEpisode?: { number: number; summary: string; ending: string; sceneTitles: string[]; continuity?: EpisodeContinuity };
  characterState: Character[];
};
export type Shot = { id: string; scene: number; episodeNumber?: number; title?: string; duration: string; size: string; camera: string; movement: string; imagePrompt: string; videoPrompt: string; negativePrompt: string; action?: string; dialogue?: string; sound?: string; characterContext?: string; characterIds?: string[]; referenceAssetIds?: string[]; referenceAssetUrls?: string[]; model?: string; status?: ShotStatus };
export type GeneratedProject = { id?: string; title: string; topic?: string; scriptLength?: ScriptLength; narrativePerspective?: NarrativePerspective; projectFormat?: ProjectFormat; episodeCount?: number; wordsPerEpisode?: number; totalTargetWords?: number; storyBible?: string; episodes?: EpisodeSummary[]; writerStyleId?: string; directorStyleId?: string; finalVideoUrl?: string; logline: string; script: string; continuity?: EpisodeContinuity; characters?: Character[]; scenes: { id?: string; number: number; episodeNumber?: number; title: string; content: string; mood: string }[]; shots: Shot[]; engine?: "local" | "penshot" | "llm" };
